# Create a new post video
POST http://localhost:3333/api/post/create/video HTTP/1.1
Content-Type: application/json

{
  "type": "video",
  "tags": ["Altay", "Republic"],
  "userId": "645a612d79d863a764bb702e",
  "status": "draft",
  "title": "Смешные видео о котиках",
  "video": "https://www.youtube.com/shorts/zIPcRpVK-i8"
}

###
# Create a new post photo
POST http://localhost:3333/api/post/create/photo HTTP/1.1
Content-Type: application/json

{
  "type": "photo",
  "tags": ["Altay", "Republic"],
  "userId": "645a612d79d863a764bb702e",
  "status": "draft",
  "title": "Очень смешные видео о котиках",
  "photo": "https://www.youtube.com/shorts/zIPcRpVK-i8"
}

###
# Create a new post quote
POST http://localhost:3333/api/post/create/quote HTTP/1.1
Content-Type: application/json

{
  "type": "quote",
  "tags": ["Altay", "Republic"],
  "userId": "645a612d79d863a764bb702e",
  "status": "draft",
  "title": "Смешные видео о котиках",
  "video": "https://www.youtube.com/shorts/zIPcRpVK-i8"
}

###
# Create a new post text
POST http://localhost:3333/api/post/create/text HTTP/1.1
Content-Type: application/json

{
  "type": "text",
  "tags": ["Altay", "Republic"],
  "userId": "645a612d79d863a764bb702e",
  "status": "draft",
  "title": "Смешные видео о котиках",
  "video": "https://www.youtube.com/shorts/zIPcRpVK-i8"
}

###
# Create a new post link
POST http://localhost:3333/api/post/create/link HTTP/1.1
Content-Type: application/json

{
  "type": "video",
  "tags": ["Altay", "Republic"],
  "userId": "645a612d79d863a764bb702e",
  "status": "draft",
  "title": "Смешные видео о котиках",
  "video": "https://www.youtube.com/shorts/zIPcRpVK-i8"
}

###

# Get post by ID
GET http://localhost:3333/api/post/3 HTTP/1.1

###

# Get posts list
GET http://localhost:3333/api/post/ HTTP/1.1

###


# Delite post by ID
DELETE  http://localhost:3333/api/post/12 HTTP/1.1

###
