# Create a new post text
POST http://localhost:3333/api/post/create HTTP/1.1
Content-Type: application/json

{
  "type": "video",
  "tags": "Алтай, Озера, Мультинские",
  "userId": "123",
  "status": "draft",
  "title": "user@notfound.local",
  "anonce": "2012-02-22",
  "text": "Keks",
  "lastname": "Smith",
  "password": "123456",
  "video": "video",
  "link": "video"

}

###

# Create a new post link
POST http://localhost:3333/api/post/link HTTP/1.1
Content-Type: application/json

{
  "type": "link",
  "tags": "Алтай, Озера, Мудьтинские",
  "userId": "123",
  "status": "",
  "link": "Keks",
  "lastname": "Smith",
  "password": "123456",
  "discription": "123456"
}

###

# Get user by ID
GET http://localhost:3333/api/post/1 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###
